<!-- Content Report Dashlet -->
<style type="text/css" media="screen">
@import "${page.url.context}/res/components/reports/css/demo_table.css";
@import "${page.url.context}/res/components/reports/css/tageditor.css";
@import "${page.url.context}/res/components/reports/css/ui.daterangepicker.css";
@import "${page.url.context}/res/components/reports/css/redmond/jquery-ui-1.8.14.custom.css";
</style>

<@link rel="stylesheet" type="text/css" href="${page.url.context}/res/components/reports/css/custom.css" />

<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/jquery-1.6.2.js"></@script>
<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/jqueryjson/jquery-json-2.2.js"></@script>
<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/jqueryui/jquery-ui-1.8.14.custom.js"></@script>
<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/jqueryui/i18n/jquery.ui.datepicker-es.js"></@script>  
<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/datarangepicker/daterangepicker.jQuery.js"></@script>
<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/datarangepicker/i18n/datarangepicker.jQuery-es.js"></@script>

<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/downloadify/swfobject.js"></@script>
<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/downloadify/downloadify.js"></@script>

<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/editinplace/jquery.autogrowtextarea.js"></@script>
<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/editinplace/jquery.editinplace.js"></@script>

 
<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/jquery.dataTables.js"></@script>

<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/raphael/raphael.js"></@script>
<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/raphael/g.raphael.js"></@script>
<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/raphael/g.pie.js"></@script>
<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/raphael/g.line.js"></@script>
<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/raphael/g.dot.js"></@script>
<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/raphael/g.bar.js"></@script>                                                                

<@script type="text/javascript" src="${page.url.context}/res/components/reports/js/dashlet.content.report.js"></@script>